name: update-ddbb

on:
  schedule:
    - cron: '*/5 * * * *' #Execute every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install necessary libraries
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          URI: ${{ secrets.URI }}
        run: python update_real_data.py
